### ISSUE TITLE
(Improvement/fix) Replace current "repeat once" button with loop song/all button, and reimplement repeat once as separate button

### ISSUE THREAD

**Issue by minusfourty** [HardcodeCoder/PulseMusic#26]
The industry standard in music players for the repeat sign is to repeat the current playlist/album endlessly, and the repeat sign with a 1 in it indicates to repeat the current track endlessly. While from a programing standpoint a loop with a number attached indicates number of loops, on every media player I have ever seen (spotify, VLC, Windows media player, every MP3 player I've ever seen, etc), repeat means to loop endlessly, not to repeat once. This makes the repeat function in an otherwise very intuitive and clean interface very misleading, implying the existence of a completely different feature.

**Comment by HardcodeCoder** [comment]
There isn't any industry standard as to how repeat works. 

There are three icons for repeat: one with grey color that represents "no repeat", repeat/loop icon with accent color "repeat the current track endlessly" and repeat with 1 in it means to "repeat only once", otherwise why would you put a 1 in the icon itself? 

I can see other music player have loop instead of repeat (YT Music for example shows repeat 1 icon but loops endlessly, where as Spotify has a loop icon (although labelled repeat) for repeating endlessly.

I will replace the repeat with loop functionality.

**Comment by minusfourty** [comment]
Thanks, I see what you mean now. My guess is that this "Industry Standard" with most media players nowadays (labeling a loop as repeat) was set by Apple with the iPod, I can see why from an outside perspective it wouldn't make sense.

**Comment by HardcodeCoder** [comment]
The repeat once icon has been replaced with a new icon. When enabled the current track repeats endlessly, until the user manually skips the track (either by clicking on skip next/previous icon in the notification or in app), which disables repeat and skips the track
