### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by subbu6338** [HardcodeCoder/PulseMusic#27]
Please add tag editor, lyrics support

**Comment by Karthick-Pandian** [comment]
Increase the bottom tab size.

**Comment by jetrosut** [comment]
Although it is against the Unix philosophy as the app would be more than doing one thing, I don't often come across apps that follow the Unix philosophy on Android anyway, which is understandable since switching to another app just to do a little thing is unintuitive. If possible, being able to edit tags within the app would be quite useful.
