### ISSUE TITLE
Support for playing .opus files

### ISSUE THREAD

**Issue by Firstbober** [HardcodeCoder/PulseMusic#33]
I recently installed PulseMusic and found that my collection of music is not detected. I quickly realized that only one song in my collection with .mp3 extension shown up. AIMP and build-in music playing app already supports .opus so supporting it in PulseMusic would be great.

**Comment by HardcodeCoder** [comment]
Does `.opus` files shows up in the library section of Pulse msuic?
Can you please provide additional details such as:
1. Android version you are using.
2. Whether or not your songs are stored in device storage or external sd cards.
3. And which Device you are using and OS.

**Comment by Firstbober** [comment]
>Does .opus files shows up in the library section of Pulse msuic?

No, only that `.mp3` file.

>1. Android version you are using.
>2. Whether or not your songs are stored in device storage or external sd cards.
>3. And which Device you are using and OS.

1. 7.1.2
2. External SD Card formatted as internal memory.
3. Wiko View 16 GB (v12bnlite)

**Comment by HardcodeCoder** [comment]
In my device `.opus` files shows up and plays correctly(Android 10). Not sure why it doesn't show up in yours. The most probable issue would be with android's `MediaStore` not indexing your `.opus` files (android not recognising `.opus` extension as a media file)

- Try to copy or move some of your `.opus` files to device storage and see if the files show up in Pulse Music.
- Secondly, try to use the  **Track Picker** option in the Home section and select the `.opus` file and see if it plays.
- If none works try renaming the files to `.ogg` and it should play fine.

The reason why your default media player and AIMP recognises `.opus` files is because those app's might be scanning your storage manually for media files, where as Pulse Music replies on android's `MediaStore` to get songs from your storage. So if `MediaStore` doesn't have it, unfortunately there isn't much i can do.

**Comment by Firstbober** [comment]
> Try to copy or move some of your .opus files to device storage and see if the files show up in Pulse Music.

Changes nothing.

> Secondly, try to use the Track Picker option in the Home section and select the .opus file and see if it plays.

Picker shows `.opus` files grayed out.

> If none works try renaming the files to .ogg and it should play fine.

After doing this it plays fine.

So it seems that `MediaStore` is the problem. I think it can get closed now.
