### ISSUE TITLE
Controls are not displayed correctly

### ISSUE THREAD

**Issue by Beowulf2** [HardcodeCoder/PulseMusic#39]
### Steps to reproduce
1. Open App
2. press on a title
3. music starts playing

### Expected behaviour
- footer bar with controls should be displayed above the navigation bar

### Actual behaviour
- footer bar with controls are partially displayed behind the navigation bar

### Environment data
Android version: 9

Device-Model: Moto G6

App version: 4.0.5

### Screenshot
![Screenshot_20210117-172322](https://user-images.githubusercontent.com/60288895/104849208-e0140f00-58e8-11eb-92be-6f4efda18591.png)

**Comment by HardcodeCoder** [comment]
Intresting. Are you able to scroll all the way to the bottom?
I think the second issue #41 results due to this. 
If you are comfortable working with developer options, please go to the Developer options and enable "Show Layout bounds" options and then open the app and post the screenshot. That will help.

**Comment by Beowulf2** [comment]
Yes, I'm able to scroll all the way down...
Screenshot will follow...

**Comment by Beowulf2** [comment]
Ok, theres a padding, above the controls, if this is gone it should be shown normal...
![Screenshot_20210117-192610](https://user-images.githubusercontent.com/60288895/104852221-ea8ad480-58f9-11eb-8c99-0dcf1e9f4944.png)

**Comment by Beowulf2** [comment]
> Ok, theres a padding, above the controls, if this is gone it should be shown normal...

The padding as the exact same size like the notification bar, maybe this help...

**Comment by HardcodeCoder** [comment]
Why did you close the issue? Is it fixed?

**Comment by Beowulf2** [comment]
No sry, yesterday it was very late and i thought i was in another project ;)

**Comment by HardcodeCoder** [comment]
I tested this on an Android 9 device and able to reproduce it. 
I also notice strange behavior in Current Queue playlist.

Just wanted to confirm if you are also facing this:
Play any track from library/home section and go to Playlist -> Current queue.
The playlist art is misaligned at the top, rather than being aligned to the back button at the top.

Can you provide a screenshot of that screen?

My testing so far reveals that using `CoordinatorLayout` with `android:fitsSystemWindows="true"` in android 9 is behaving differently than on android 10.

**Comment by Beowulf2** [comment]
Yes, I have the same misaligned playlist arts.  
![Screenshot_20210118-163204](https://user-images.githubusercontent.com/60288895/104935365-6db83300-59ab-11eb-8c96-5878228a3995.png)  

Maybe under Android 9 it pays no attention for the notification bar?  

> Ok, theres a padding, above the controls, if this is gone it should be shown normal...
> ![Screenshot_20210117-192610](https://user-images.githubusercontent.com/60288895/104852221-ea8ad480-58f9-11eb-8c99-0dcf1e9f4944.png)

Like I said here, the padding has exact the same size, like the notification bar.

**Comment by HardcodeCoder** [comment]
Yes, I have figured out the issue. Don't know why that happens but `WindowInsets` is getting applied in both the places where as in android 10 it's not getting applied. Don't know which one is the expected behaviour. 
I have fixed this issue, currently testing. :)

**Comment by Beowulf2** [comment]
Some times Android is really strange... I know ;)

**Comment by Beowulf2** [comment]
/open
Problem with the album art is fixed, but this still exist 

> ![Screenshot_20210117-192610](https://user-images.githubusercontent.com/60288895/104852221-ea8ad480-58f9-11eb-8c99-0dcf1e9f4944.png)

**Comment by Beowulf2** [comment]
Problem with the album art is fixed, but this still exist 

> ![Screenshot_20210117-192610](https://user-images.githubusercontent.com/60288895/104852221-ea8ad480-58f9-11eb-8c99-0dcf1e9f4944.png)
