### ISSUE TITLE
Clone of another app

### ISSUE THREAD

**Issue by Beowulf2** [HardcodeCoder/PulseMusic#43]
Why did you just copy the app from somewhere else without any copyright notice?

**Comment by HardcodeCoder** [comment]
Can you please explain which app you are referring to? This is not a clone of any other app. Check the entire source code jone of the code is copied from any other app. However the settings page UI is highly inspired from lawnchairs serrings page.

**Comment by Beowulf2** [comment]
I found this app: https://github.com/h4h13/RetroMusicPlayer

**Comment by HardcodeCoder** [comment]
Any why you think its a clone?

**Comment by Beowulf2** [comment]
It looks very similar (from the complete construction (frontend)), but if you say it's not a clone, then I trust you.

**Comment by HardcodeCoder** [comment]
No  you don't have to trust me in any way.
Let's clear this out.
1. Retro Music didn't look the same the way it looks today (Mostly because they follow Google's app design and so does Pulse Music (Check older versions of Google photos, Drive, Gmail, Notes, playstore)). I initially implemented the Top Albums, Top Artist section along with the shortcuts after getting inspiration from Gaana app (an Indian online streaming app). Later I moved the shortcuts to the top of the screen as it looks better. Afaik  Retro music used to have some greetings kind of section at the top and not these shortcuts. 

2. Settings section (Only UI) is highly inspired from Lawnchair app. I am assuming that Retro Music's Settings page is also inspired from lawnchair and hence all looks the same.
3.  Other sections like Library , Albums, Artist are mostly the same across a wide range of music player (kind of a standard design choice these days)
4.  Playlist section is my own implementation from the ground up. In fact I have a custom implementation to store playlist where as most other apps rely on frameworks `MediaStore`.

I understand why people think it's a clone, mainly because they looks the same and the fact that Retro Music is more popular than PulseMsuic, so that means the less popular app must be copied from the popular one. 

To conclude, If I had used any code from any other app/project (copy and paste) I would love to give them proper credit.
Having a specific UI/feature does not necessarily means that one is a clone of the other (if the implementation and functionality is different). 
There are thousands of questions on SO, asking how they can implement this UI featured in spotify/Google's app/some other app, etc.. The implementation is definitely different but achieves similar features/design. So, that doesn't make them clones. 

I personally have used RetroMusic in the past (before I developed this app ofcource), and that's the reason why I think I subconsciously had those designs in mind while I was working on PulseMusic.

Lastly, you can check the commit history and get an idea as to how the app has evolved over the years.

I hope this might clear the confusion. :)

**Comment by HardcodeCoder** [comment]
Sorry for that long explanation. Anyways I will soon be redesigning most the UI so as to make it look different. I don't want people to think It's a clone.

**Comment by Beowulf2** [comment]
Thank you very much for the execution.  
The execution is very conclusive for me.
