### ISSUE TITLE
Music cover art not show up on Android 11

### ISSUE THREAD

**Issue by TeGaX** [HardcodeCoder/PulseMusic#48]
I'm using One UI 3 Android 11 based, when I use other music app the music cover art still show up normal, but Pulse Music is no even I had to reset app or reinstall app with the latest ver but still can't be fixed
Hope you can do something to make it work, I like Pulse Music very much

**Comment by Ksanbah** [comment]
Hi I'm using Color OS 11, Android 11 and the cover art are not visible.

**Comment by RilicTheFox** [comment]
On CRDroid 7.0 (Android 11). It looks like the albums aren't being grouped together, either. When I try to open an album, it doesn't show its tracks. I can still play individual songs, though.

**Comment by HardcodeCoder** [comment]
That may be the case since  SAF was optional on Android 10, but is going to be mandatory with future versions of Android. So there must be changes to the system that prevents older implementation (particularly affecting MediaStore). 

One of the hilarious thing is that, most of the music player app on android including Pulse Music uses a completely undocumented (and may be unofficial and private) uri to access the album art, but thats the only way to consistently get album art on all android versions and the only answer you find on StackOverflow. But looks like it doesn't work on Android 11 and hence this bug. 

The only temporary fix for now seems to opt out of SAF, and that might fix the issue(untested). But I am looking for a permanent solution else I will implement a custom logic to cache and load album art

**Comment by subhajit-halder** [comment]
Bumping this issue. I'm on MIUI 12 with Android 11. The album art doesn't show up. 

Other than that this is a great app 👍. Would you release this on Play Store as well?

**Comment by Karthick-Pandian** [comment]
I don't want album art. It's distracting
