### ISSUE TITLE
Sort by track number doesn't account for albums with multiple "discs"

### ISSUE THREAD

**Issue by JCDetwiler** [HardcodeCoder/PulseMusic#52]
The sorting only accounts for track number, resulting in:

    Disc 1, Track 1
    Disc 2, Track 1
    Disc 1, Track 2
    Disc 2, Track 2
    ...

when the desired behavior would be

    Disc 1, Track 1
    Disc 1, Track 2
    ...
    Disc 2, Track 1
    ...

**Comment by HardcodeCoder** [comment]
This issue was already addressed [here](#24) and closed.
It looks like MediaStore does not encode disc number along with track number as per the documentation [here](https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns#TRACK).
This is true for my testing (on Android 10) as well. `MedisStore` simply does not encode disc number even if track metadata has it. So there isn't much I can do from my side as we completely depends on `MediaStore` for track metadata.


If you are able to verify that other application(s) can sort your albums according to the disc number but PulseMusic cannot, please reopen this issue.

**Comment by JCDetwiler** [comment]
Oh good grief, it's part of the Android development tools? No wonder it's a bug in every single music player I've tried out. Thanks anyway then.

PS, you linked to my issue when you said it was already addressed.

**Comment by HardcodeCoder** [comment]
Oops! My bad. I have updated the comments.
