### ISSUE TITLE
[Feature Request] Remove queue group & Remove song from the queue

### ISSUE THREAD

**Issue by putulopi** [HardcodeCoder/PulseMusic#66]
- I cant remove a queue that i just created, especially the default (now playing) queue
- I cant remove a song from the queue group, i was accidentaly add the song that i dont want in that group and i cant delete it.

**Comment by HardcodeCoder** [comment]
Please provide a description of the feature you mentioned.

**Comment by HardcodeCoder** [comment]
> I cant remove a queue that i just created, especially the default (now playing) queue

You **cannot** delete the **Playing queue** playlist (as it handles the active tracks) all other user created playlist can be deleted by a **_left swipe_** gesture. 

> I cant remove a song from the queue group, i was accidentaly add the song that i dont want in that group and i cant delete it.

You need to **_swipe left_** to remove a song from any playlist (both Playing queue and User created playlist(s))

Closing the issue because the feature(s) you requested already exits. 
If this is not what you are looking for please reopen the issue.
