### ISSUE TITLE
Separate albums by disc on multi disc albums

### ISSUE THREAD

**Issue by MateusRodCosta** [HardcodeCoder/PulseMusic#74]
Hi, so I found out about this music player today and it seems very good and I would like to try using it in the future.

However there's one feature that I use that prevents me from using this app it as-is since it's not implemented right now: Separating the album by its discs.

I think some context might help explain why I need it:

1) Since a while ago I try to store my music in opus, so I generally get them in FLAC and convert to 129 kbps opus;
2) I usually use Picard to corrrect the metadata of my music, one side effect of that is that generally it turns multi-disc albums that would be split int on album for each disc into a single album where the tacks are marked with which disc they belong to;
3) I usually have among my music Videogame OSTs, those sometimes are a single disc, other times they can range from 2 to 5 discs.

1 is not very relevant, but only on Android 10 it was finally possible to play .opus files in a normal (MediaStore based?) music player (before Android 10, I could play them as long as they had the .ogg extension, but I decided to use VLC instead).

2 and 3 are relevant here. Among my music I have the [Chrono Trigger OST](https://en.wikipedia.org/wiki/Music_of_Chrono_Trigger#Chrono_Trigger_Original_Soundtrack_(2009_release)) which is composed of 3 discs. Thanks to Picard and MusicBrainz, they are a single album, split into discs by the metadata.

Generally, this has the effect that every single music player on Android shows first all the tracks 1 from every disc, then all tracks 2 from all discs and so on, the only exception so far being VLC.

Here are some screenshots to illustrate my point.

Lollypop, the player I use on Linux desktop, supports this:

![Captura de tela de 2021-02-18 21-17-26](https://user-images.githubusercontent.com/24463334/108438808-c8ed7780-722e-11eb-91e4-ec664df4e927.png)

![Captura de tela de 2021-02-18 21-17-33](https://user-images.githubusercontent.com/24463334/108438842-da368400-722e-11eb-8195-b4a239e55cc1.png)

Notice how it shows all tracks for disc 1, then all the tracks for disc 2

This is VLC, the only audio player I found that actually does what I would like:

![image](https://user-images.githubusercontent.com/24463334/108439422-fdadfe80-722f-11eb-8f8c-104e198c7512.png)

And here's Pulse Music ordered by track asc:

![image](https://user-images.githubusercontent.com/24463334/108439578-52517980-7230-11eb-89eb-77e7847fd58f.png)

Notice how it starts with the track 1 of the second disc, then track 1 of the first and track 1 of the third

Since I only ever saw VLC respecting the disc number information, I thought at first that it was something custom that its devs made. However apparently [it's something present in the MediaStore APIs](https://developer.android.com/reference/android/media/MediaMetadataRetriever#METADATA_KEY_DISC_NUMBER) which only VLC bothered to implement and other players ignored (which is understandable, since only a subset of users would need it)

Would it be possible to implement this? I'm not sure how much of the feature would be enough, IMHO I would think of at least:

* The album page shows tracks separated by disc in order of discs, with tracks in order by track number of that disc
* Tapping a track would play starting from that track and play the other tracks in order and when finishing a disk, the next one would start playing

Thanks!

**Comment by HardcodeCoder** [comment]
- Similar requests had already been made, see #52 and #24. I have already implemented the logic to sort albums based on disc and track number (see [commit](https://github.com/HardcodeCoder/PulseMusic/commit/36f2eb0c976d1867a4405260cdaced968ad73a67)). 

- You correctly pointed out the API through which one can extract the disc number, but that's not how music players (generally) are designed. 

- There is a class called the [MediaStore](https://developer.android.com/reference/android/provider/MediaStore), the android system internally uses the `MediaMetadataRetriever` to extract the data from audio files and stores them in `MediaStore` and provides an interface through which most of the media player apps (including pulse music) gets the data. This is efficient, because we simply ready the stored data (which for the most part is accurate and up to date), rather than extracting metadata from each audio file, each time the application is launched. 

- Just like this  API you [pointed out](https://developer.android.com/reference/android/media/MediaMetadataRetriever#METADATA_KEY_DISC_NUMBER) (which is actually a `MediaMetadataRetriever` api and does not belong to `MediaStore` ), `MediaStore` also has a similar api called [MediaStore.Audio.AudioColumns.TRACK](https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns#TRACK), which (as per the documentation) encodes both the disc and track number.

- However, it actually does not. Yes, although the documentation says it does encodes, there is no such information available in the database (tested on stock A10, A9 and some other third party OS), hence almost all the music player shows a similar behavior, and does not respect the disc number, because there isn't one (weird I know).

-  As for VLC, well they have their own libraries and loaders and doe not depends on android's `MediaStore` for metadata (At least this is what seems to be logical, I have not explored the source code much).

**Why PulseMusic does not use `MediaMetadataRetriever` and get the metadata by itself?**

Because, it's an expensive operation, We could use a internal database and cache everything, but still every time we open the app, we must refresh the database. Also, we need to write a lot of custom logic (which currently `MediaStore` handles). There are ways to get around it and make it efficient, but as you might guess it's a lot of work for a feature that most of the general users does not care about. 

One alternative which I was thinking for a while is to extract the metadata (of only those audio files that belongs to the given album) when the user opens the Albums page. But looking at your user case (you have 70 tracks in a single album), this might still be expensive and can cause a lot of delay before the data actually appears on the screen. 

I am closing this issue for now. I will see if this can be fixed (some how).

**Comment by MateusRodCosta** [comment]
First of all, thanks for the detailed explanation on why it isn't feasible to implement it currently!

I did take a look at [MediaStore.Audio.AudioColumns](https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns) and apparently up to Android 10 things happens as you say: there's only the TRACK api which brings the disc number along with the track number.

However I also took a look at [MediaStore.MediaColumns](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns), from which AudioColumns apparently inherits. It seems Android 11 added two new apis which should help here: [MediaStore.MediaColumns.CD_TRACK_NUMBER](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#CD_TRACK_NUMBER) and [MediaStore.MediaColumns.DISC_NUMBER](https://developer.android.com/reference/android/provider/MediaStore.MediaColumns#DISC_NUMBER).

If you do manage to get ahold of an Android 11 device (maybe an AVD works as well?), could you test whether those help?

It will probably take a while until I am able to upgrade to an Android 11+ device, but knowing that when I do I can use MediaStore-based music players without this problem would be very cool!

**Comment by HardcodeCoder** [comment]
Thanks for pointing that out. Those apis can solve this issue for at least Android 11 devices (Hopefully they actually have useful data, will need to test on actual A11 device(s) so might take some time).
I will definitely look in to it.
