### ISSUE TITLE
Feature request: built-in media scanner

### ISSUE THREAD

**Issue by dalaeance** [HardcodeCoder/PulseMusic#75]
It'd be cool if there was a way to force scanning of storage—or specific directories—for new media. 

For some reason, newly-added music wasn't automatically showing up unless it _wasn't_ in a subfolder in the `/Music` directory. I tested this by copying a track from `/Music/subfolder` to `/Music`, and that's when it showed up in the app.

To be fair, this behaviour was observed in Pulse Music, Odyssey, and Simple Music Player. I had to download an outdated app from F-Droid called SD Scanner to force the update. Surprisingly, it worked.

**Comment by HardcodeCoder** [comment]
As for your issue, if newly added media does not automatically appear in the app try restarting the device (This triggers the Media Scanner to re scan your storage for media files).

Manually scanning of storage is not really an option anymore due to [strict restrictions](https://developer.android.com/guide/components/broadcast-exceptions) on Broadcast receivers(which is what applications use to trigger the Media Scanner).

>  I had to download an outdated app from F-Droid called SD Scanner to force the update. Surprisingly, it worked.

Once these app targets to newer API levels, it won't work (These restrictions are imposed only if applications target newer API).

**Comment by dalaeance** [comment]
That's a bummer. I think I'll hang on to SD Scanner, then; I'd rather not have to restart my phone every time I add media. It's good to know it being outdated is an asset in this case.
