### ISSUE TITLE
[Feature-Request] Shuffle button to randomize next song.

### ISSUE THREAD

**Issue by d4f5409d** [HardcodeCoder/PulseMusic#77]
### (Intelligent) Shuffling and editing

Hello! I wanna request two features.
The first is you could add song shuffling so it would add randomness to the songs. I would also like intelligent shuffle, which know which songs have been played in the past minutes, so it wouldn't play the same song when shuffling in like 15 mins.
The second feature is editing song names and infos inside the app. This pretty much tells what I've wanted, I think.
Thank you for your work! Keep it up!

**Comment by HardcodeCoder** [comment]
In Pulse Music everything is considered a playlist (Whether playing from search, Home section, Library etc.) 
The shuffle feature can be implemented (for a given playlist) in two ways:
- Using a time constraint like you mention.
OR
- Shuffling the rest of the tracks in the playlist  after the current track.
For example: If the active track index is 4, we will shuffle all track from 5 so that the next song in queue will have some randomness. By default all generated playlist do not contain duplicates (except user created playlist, where duplicates are allowed but can be cleared using the toolbar option -> Remove duplicates)
In my opinion this will cover up your requirement to not repeat the tracks, and add randomness to the songs. 

Let me know if I missed something here.

P.S: There are already open issue(s) for feature request: Editing song info. See #27

**Comment by d4f5409d** [comment]
Yes! This is what I wanted. Thank you!
Sorry for my bad English.

**Comment by PEPERSO** [comment]
I agree, adding a shuffle button to the "Now playing" page would be very useful to me

But thanks for Pulse, it is **awesome** :1st_place_medal: !

**Comment by HardcodeCoder** [comment]
Since there is already a dedicated issue for editing metadata ( #27 ), updating the title to reflect the shuffle feature.
