### ISSUE TITLE
Not all songs are showing in playlist

### ISSUE THREAD

**Issue by pokegamer5547** [HardcodeCoder/PulseMusic#78]
In a lot of my playlists, not all songs of that playlists are showing in pulse music app songs list. Some of the song's which are in same folder are missing. (Don't know how to reproduce this bug)
![IMG_20210302_113408](https://user-images.githubusercontent.com/65234485/109605630-76279000-7b4b-11eb-8d7d-bf7202da2b01.jpg)
![IMG_20210302_113439](https://user-images.githubusercontent.com/65234485/109605654-80e22500-7b4b-11eb-9d0e-8c778acb7e99.jpg)

**Comment by HardcodeCoder** [comment]
- Make sure you have not accidentally blacklisted some of the folders where the album tracks are stored. 
- Try copying all the songs of the album in same folder and restart the device.

We rely on `MediaStore`, for getting all the albums and its tracks. If for some reason `MediaStore` does not have those tracks under the same album, PulseMusic will fail to show those tracks.

**Comment by pokegamer5547** [comment]
I removed all blacklisted folders, and made sure all of the songs are in same folder. It fixed the problem for the playlist I showed in the screenshot. But for other albums it's still the same, I double checked again for other albums to make sure they're in same folder and restated the device but still no change.

**Comment by HardcodeCoder** [comment]
Please provide the following info:
1. Android version.
2.  OS
3. Device

**Comment by HardcodeCoder** [comment]
There are two possible cases:
1. Invalid album id in Pulse Music (which has been fixed and included in the upcoming release).
2.  Album ids of those tracks are different, hence they do not appear in the same album (Check if the other tracks appears in some other album (probably with the same name)).

As for (1) wait for the next release, and verify if the issue persists. 

For (2) this happens probably because the `MediaStore` is not indexing your albums correctly. Try to create a new folder for each of your albums.

 As a last resort, you can clear the `MediaStore` database (Go to Device settings -> Apps -> System Apps -> Media storage. Clear data and cache and restart your device). 
This will clear the index of all your audio files, images, documents. Even though actual files on your device will not be deleted, still use this with caution.

**Comment by PEPERSO** [comment]
May be it is because tracks are too short and so they are filtered by your General > "Filter duration" ? Try to set it to 0, and see if it fixes your issue

**Comment by pokegamer5547** [comment]
> May be it is because tracks are too short and so they are filtered by your General > "Filter duration" ? Try to set it to 0, and see if it fixes your issue

Thankyou,I have tried that already but it didn't fired the issue.

**Comment by HardcodeCoder** [comment]
@pokegamer5547 Is the issue still present in `V4.1.0`?

**Comment by pokegamer5547** [comment]
> @pokegamer5547 Is the issue still present in `V4.1.0`?

I'm not sure,I didn't received the latest update of this app in fdroid yet.i will let you know once I get the update.(I use fdroid since it's easy for me to check updates by that)

**Comment by pokegamer5547** [comment]
This issue has been finally fixed for me in latest update. Thanks a lot@HardcodeCoder ! :) (Also idk why but latest update still not available in f droid so I downloaded from GitHub, please fix that.)

**Comment by HardcodeCoder** [comment]
That's great. I will close this issue now. As for f-droid there is an [issue](https://gitlab.com/fdroid/admin/-/issues/202) with their build system, hence the update is not published yet.
