### ISSUE TITLE
Add seek buttons

### ISSUE THREAD

**Issue by Pranab009** [HardcodeCoder/PulseMusic#80]
Please add seek (10sec) buttons inside the app and also in notification panel.
Don't you throughout it is a basic & handy feature.
Please add this.

**Comment by HardcodeCoder** [comment]
> Please add seek (10sec) buttons inside the app and also in notification panel.

I won't add seek buttons in notification, as there is already seek bar in A 10+ devices, which serves the same purpose.
And seek buttons in UI is already there: Settings -> Now Playing -> Enable seek buttons.

I see that you have already created an older issue for this exact same feature #36. It will be better if you can take a moment to see if the issue is already reported and or closed.

> Don't you throughout it is a basic & handy feature.

No, I don't think it is.

**Comment by Pranab009** [comment]
Sorry but I'm still using 4.0 (fdroid) version.

**Comment by HardcodeCoder** [comment]
@Pranab009 Update to latest V 4.1.0, it has been implemented in the latest release, or wait for the update from f-droid.

**Comment by Pranab009** [comment]
Ok I'm download it.
Sorry once again. Please don't mind,
