### ISSUE TITLE
Bug: When changing tracks seek bar in notification seeks before resetting

### ISSUE THREAD

**Issue by main-character** [HardcodeCoder/PulseMusic#95]
Hi the notification for pulse music is kinda buggy because of the time seeker in it. Whenever i seek songs, the seeker isnt in the correct play time. Some maybe unbothered by it but some may do. So it would be awesome if we could have a settings where we could somehow disable the seeker in the notification drawer.

**Comment by HardcodeCoder** [comment]
As for the 'notification is kinda buggy' , provide a video or screenshot that demonstrate the issue, and also state the expected behavior.

Pulse uses the standard `MediaStyle` notification provided by the android system. It's not possible to completely remove the seekbar, only the seek functionality can be disabled (but we will still have the progress bar showing the duration).

**Comment by main-character** [comment]
I cant send a video but ill try my best to explain the situation. Whenever i use the seeker and skip the song in the notification panel, the seeker would first go back or forth for a few seconds and then change to a new song. 

I think it would be better if we remove the seekbar or atleast give an option to disable so. 

It's okay if the progress bar is still there as long as the seeker isn't.

Thank you and i'm a big fan

**Comment by main-character** [comment]
Hi its me again

this is [pulse music](https://drive.google.com/file/d/1LNyyfngectCnAZGnnO7MXtjcmNLxwL06/view?usp=sharing) playing in the notification. As you can see, the seeker either moves forward or backwards before changing into a new song. 

My expected behavior would like the notification of [Auxio Player ](https://drive.google.com/file/d/18X0VCjoY_ir5mXlQYVKoxkocuHOjVStU/view?usp=sharing). It disappears completely and starts again.
